---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# explorers

<!-- badges: start -->
<!-- badges: end -->

The goal of explorers is to ...

## Installation

You can install the development version of explorers from [GitHub](https://github.com/WouterVerra/explorers) with:

``` r
# install.packages("devtools")
devtools::install_github("WouterVerra/explorers", build_vignettes = TRUE)
```

## functions

#### explore
The explore function takes my most used functions when exploring a new dataframe and lists the output from 1 command. 

#### NAcol
The NAcol function is another exploratory function which finds how many NA values are present in every column of a dataframe. 

#### NArow
The NArow function is also an exploratory function that finds how many NA values are present in every row of a dataframe. 

#### replace
The last function of this package is the replace function which replaces an old value to a new value inside of a specified column of a dataframe.

## data

#### soccer:
A dataset containing the points scored, assists made and teams played of a made-up soccer player.
